### ISSUE TITLE
Error - Online tool

### ISSUE THREAD

**Issue by vanessafernandezvidueira** [prisma-flowdiagram/PRISMA2020#44]
When I upload a customised csv file and try to create a diagram I get the following message: "An error has occurred. Check your logs or contact the app author for clarification". Any suggestions of what to do or why this is happening? Thanks a lot!

**Comment by chriscpritchard** [comment]
Hello @vanessafernandezvidueira,

Unfortunately at the moment the webapp doesn't have hugely descriptive error messages, but usually this is due to an error in the formatting or content of the CSV file (which is a little bit picky in terms of how it's set up). If you'd like, I can take a look if you're happy to send me the CSV file you're trying to use.

Please send it to chris@christopherpritchard.co.uk and I can take a look.

**Comment by chriscpritchard** [comment]
Thank you for sending the CSV across. As highlighted it seems to be an issue with the CSV file itself rather than the tool so I'll close this issue.
