### ISSUE TITLE
High resolution PRISMA flowchart in compliance with journal requirements

### ISSUE THREAD

**Issue by qianjzhang** [prisma-flowdiagram/PRISMA2020#56]
**Is your feature request related to a problem? Please describe.**
No. But is there a way to generate the flow diagram image in 600 or higher dpi? Many journal publishers require high resolution figures. The PRISMA flow diagram on Shiny is in low resolution.

**Comment by chriscpritchard** [comment]
Not directly at the moment, but SVG is a vector format that can be converted via whatever means you would like into a high DPI raster format such as PNG. That said, you may be able to submit an SVG directly to some / most journals and would be the best format because the text is actually text (and therefore works with screen readers etc)

**Comment by qianjzhang** [comment]
Thank you! I have additional question about the flow diagram. Is there a way to remove 
Databases (n=0) and Registers (n=0) 
Records marked as ineligible by automation tools (n=0) and Records removed for other reasons (n=0)?

**Comment by chriscpritchard** [comment]
Yes, just delete the number from the field or csv and the app automatically removes the text!

**Comment by qianjzhang** [comment]
Thank you! So maybe I should add the numbers to the CSV file, upload to the Shiny App and then download the SVG file?  I also need to remove new studies included in review and reports of new included studies. Can I just remove them in the CSV file too? Many thanks!!

**Comment by chriscpritchard** [comment]
Since this wasn't a bug / feature request but a query, I'm closing this as an issue.
