### ISSUE TITLE
Total studies included in review not appearing

### ISSUE THREAD

**Issue by qianjzhang** [prisma-flowdiagram/PRISMA2020#57]
**Describe the bug**
When I do not include previous studies, the total studies included in review and reports of total included studies disappear. Our review does not include any previous studies. But we do need the grey box of total studies. 

**To Reproduce**
1. Go to 'Previous studies'
2. Click on 'No Included'
3. See error: The grey box of 'Total studies included in review and reports of total included studies' disappear 

**Expected behavior**
still have the grey box of 'Total studies included in review and reports of total included studies' no matter there are previous studies.

**Screenshots**
![issue_pic](https://github.com/prisma-flowdiagram/PRISMA2020/assets/27222855/c1431778-8ebd-4d2a-a6b3-b35b0258777c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version not known

**Additional context**

**Comment by chriscpritchard** [comment]
This is in line with the PRISMA2020 flow diagram standards - http://prisma-statement.org/prismastatement/flowdiagram.aspx

This is because the total studies and reports of total included studies would be equal to new studies and reports of new included studies. You can amend the text from new studies included in review to Total studies included in review by modifying the text in the "boxtext" column of the csv - you're looking for the row with "new_studies" in the data field.

**Comment by qianjzhang** [comment]
Thank you! But the PRISMA2020 flow diagram standards contain four flow diagram documents. The first two is PRISMA 2020 flow diagram for new systematic reviews do not have the grey box of previous studies. I guess the shiny app is to create PRISMA 2020 flow diagram for updated systematic reviews.
